### PR TITLE
m2ee-tools v7.2.2

### PR DESCRIPTION
**Pull request by knorrie**
Hi, I want to do a bugfix maintenance release.

Please review, thanks.

### CODE REVIEW

**Comment by knorrie** [comment]
I added one more fix.. Have the PostgreSQL graphs continue when the app is offline. I really wonder why no customer has complained about that one yet. Or maybe they have, but it never reached me.

**Comment by RCatersels** [comment]
I never complaint because I thought there was probably a technical reason why they stopped.

**Comment by knorrie** [comment]
All graphs which are based on information that we get from the statistics calls in the runtime admin api won't show new info (that's also amount of database inserts, deletes, since we get those from connectionbus stats). But the stuff that's read from postgresql directly can be done while the application process is not running.

**Comment by igor-mendix** [comment]
Just for the record: the changes in this merge request are reviewed and are fine. Thanks to everyone involved for all the fixes!

**Pull request merged**
